version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: blameio
      POSTGRES_PASSWORD: RYc7ET6MwdjkmkbkfPJutHfh
      POSTGRES_DB: statsdb
    ports:
      - "5433:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  collectd:
    build:
      context: ./collectd # Replace with the directory containing the Dockerfile and Python script
      dockerfile: Dockerfile
    depends_on:
      - timescaledb
    env_file:
    - env.list

  grafana:
    image: grafana/grafana
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: timescaledb:5433
      GF_DATABASE_NAME: statsdb
      GF_DATABASE_USER: blameio
      GF_DATABASE_PASSWORD: RYc7ET6MwdjkmkbkfPJutHfh
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - "3005:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - timescaledb

volumes:
  timescaledb-data:
    driver: local
