{
 "title": "Diff based latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Replication lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "replication_mycollector",
     "select": [
      [
       { "params": [ "Seconds_Behind_Master" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency by table",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_io_mycollector",
     "select": [
      [
       { "params": [ "WAIT_LATENCY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "latency last 5m",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "-- SELECT \"table_name\", \"WAIT_LATENCY\" FROM latency.autogen.table_io_mycollector WHERE $timeFilter\nSELECT difference(mean(\"WAIT_LATENCY\")) as wait_latency, difference(mean(\"COUNT_STAR\")) as count_star FROM latency.autogen.table_io_mycollector WHERE  $timeFilter GROUP BY time(15m),table_name::tag\n\n"
    }
   ]
  },
  {
   "title": "Last 5m latency diff",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "alias": "$col",
     "query": "-- SELECT \"table_name\", \"WAIT_LATENCY\" FROM latency.autogen.table_io_mycollector WHERE $timeFilter\nSELECT difference(mean(\"WAIT_LATENCY\")) as WAIT_LATENCY FROM latency.autogen.table_io_mycollector WHERE $timeFilter GROUP BY time(15m),table_name::tag fill(null)\n\n"
    }
   ]
  }
 ]
}