{
 "title": "DB Master Index stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "breakdown",
    "query": "query, \"user\", state, host, trx_operation_state"
   }
  ]
 },
 "panels": [
  {
   "title": "Queries by total exec time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_trunc('minute', time) AS time,\r\n    $breakdown,\r\n    SUM(exec_time) AS total_execution_time\r\nFROM\r\n    digest_stats\r\nWHERE\r\n    $__timeFilter(time)\r\nAND db = 'master'\r\nGROUP BY\r\n    time, $breakdown\r\nORDER BY\r\n    time;"
    }
   ]
  },
  {
   "title": "Top index IOwait",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\r\n    SELECT date_trunc('minute', time) AS time,\r\n           index_name,\r\n           AVG(wait_latency) AS mean_wait_latency\r\n    FROM index_io\r\n    WHERE $__timeFilter(time)\r\n      AND db = 'master'\r\n    GROUP BY time, index_name\r\n),\r\nlag_values AS (\r\n    SELECT time,\r\n           index_name,\r\n           mean_wait_latency,\r\n           LAG(mean_wait_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_wait_latency\r\n    FROM time_buckets\r\n),\r\nindex_latencies AS (\r\n    SELECT index_name,\r\n           SUM(mean_wait_latency - prev_mean_wait_latency) AS total_wait_latency_diff\r\n    FROM lag_values\r\n    WHERE mean_wait_latency - prev_mean_wait_latency IS NOT NULL\r\n    GROUP BY index_name\r\n),\r\ntotal_latency AS (\r\n    SELECT SUM(total_wait_latency_diff) AS overall_total_diff\r\n    FROM index_latencies\r\n),\r\nindex_with_percentage AS (\r\n    SELECT index_name,\r\n           total_wait_latency_diff,\r\n           (total_wait_latency_diff / (SELECT overall_total_diff FROM total_latency)) * 100 AS percentage_of_total\r\n    FROM index_latencies\r\n),\r\nindex_with_cumulative_percentage AS (\r\n    SELECT index_name,\r\n           percentage_of_total,\r\n           SUM(percentage_of_total) OVER (ORDER BY percentage_of_total DESC) AS cumulative_percentage\r\n    FROM index_with_percentage\r\n)\r\nSELECT\r\n    CASE\r\n        WHEN cumulative_percentage - percentage_of_total > 99 THEN 'OTHER'\r\n        ELSE index_name\r\n    END AS index_name,\r\n    SUM(percentage_of_total) AS percentage_of_total\r\nFROM index_with_cumulative_percentage\r\nGROUP BY CASE\r\n            WHEN cumulative_percentage - percentage_of_total > 99 THEN 'OTHER'\r\n            ELSE index_name\r\n         END\r\nORDER BY percentage_of_total DESC;\r\n"
    }
   ]
  },
  {
   "title": "Index IOwait stats",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\r\n    SELECT date_trunc('minute', time) AS time,\r\n           index_name,\r\n           SUM(wait_latency) AS mean_wait_latency\r\n    FROM index_io\r\n    WHERE $__timeFilter(time)\r\n      AND db = 'master'\r\n    GROUP BY time, index_name\r\n),\r\nlag_values AS (\r\n    SELECT time,\r\n           index_name,\r\n           mean_wait_latency,\r\n           LAG(mean_wait_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_wait_latency\r\n    FROM time_buckets\r\n)\r\nSELECT time,\r\n       index_name,\r\n       mean_wait_latency - prev_mean_wait_latency AS wait_latency_diff\r\nFROM lag_values\r\nWHERE (mean_wait_latency - prev_mean_wait_latency) > 0\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Index iowait operation breakdown",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\r\n    SELECT date_trunc('minute', time) AS time,\r\n           index_name,\r\n           AVG(fetch_latency) AS mean_fetch_latency,\r\n           AVG(insert_latency) AS mean_insert_latency,\r\n           AVG(update_latency) AS mean_update_latency,\r\n           AVG(delete_latency) AS mean_delete_latency,\r\n           AVG(wait_latency) AS mean_wait_latency\r\n    FROM index_io\r\n    WHERE $__timeFilter(time)\r\n      AND db = 'master'\r\n    GROUP BY time, index_name\r\n),\r\n\r\nlag_values AS (\r\n    SELECT time,\r\n           index_name,\r\n           mean_fetch_latency,\r\n           LAG(mean_fetch_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_fetch_latency,\r\n           mean_insert_latency,\r\n           LAG(mean_insert_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_insert_latency,\r\n           mean_update_latency,\r\n           LAG(mean_update_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_update_latency,\r\n           mean_delete_latency,\r\n           LAG(mean_delete_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_delete_latency,\r\n           mean_wait_latency,\r\n           LAG(mean_wait_latency) OVER (PARTITION BY index_name ORDER BY time) AS prev_mean_wait_latency\r\n    FROM time_buckets\r\n),\r\n\r\nlatency_diffs AS (\r\n    SELECT index_name,\r\n           SUM(mean_fetch_latency - prev_mean_fetch_latency) AS fetch_latency_diff,\r\n           SUM(mean_insert_latency - prev_mean_insert_latency) AS insert_latency_diff,\r\n           SUM(mean_update_latency - prev_mean_update_latency) AS update_latency_diff,\r\n           SUM(mean_delete_latency - prev_mean_delete_latency) AS delete_latency_diff,\r\n           SUM(mean_wait_latency - prev_mean_wait_latency) AS wait_latency_diff\r\n    FROM lag_values\r\n    WHERE mean_wait_latency - prev_mean_wait_latency IS NOT NULL\r\n    GROUP BY index_name\r\n),\r\n\r\noverall_totals AS (\r\n    SELECT SUM(wait_latency_diff) AS overall_wait_diff\r\n    FROM latency_diffs\r\n)\r\n\r\nSELECT index_name,\r\n       ROUND((fetch_latency_diff/NULLIF(wait_latency_diff,0))*100) AS FETCH_LATENCY,\r\n       ROUND((insert_latency_diff/NULLIF(wait_latency_diff,0))*100) AS INSERT_LATENCY,\r\n       ROUND((update_latency_diff/NULLIF(wait_latency_diff,0))*100) AS UPDATE_LATENCY,\r\n       ROUND((delete_latency_diff/NULLIF(wait_latency_diff,0))*100) AS DELETE_LATENCY,\r\n       ROUND((wait_latency_diff/NULLIF(overall_wait_diff,0))*100) AS \"WAIT_LATENCY (percent of total)\"\r\nFROM latency_diffs, overall_totals\r\nWHERE wait_latency_diff > 0\r\n"
    }
   ]
  }
 ]
}