{
 "title": "Replication stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Replication lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    time,                      -- the timestamp column\r\n    Seconds_Behind_Master      -- the replication lag metric\r\nFROM \r\n    replication\r\nWHERE\r\n    $__timeFilter(time)        -- Grafana's time range filter\r\nAND db = 'replica'\r\nORDER BY \r\n    time ASC;\r\n"
    }
   ]
  },
  {
   "title": "Total latencies %",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\r\n    SELECT date_trunc('minute', time) AS time,\r\n           table_name,\r\n           AVG(wait_latency) AS mean_wait_latency\r\n    FROM table_io\r\n    WHERE $__timeFilter(time)\r\n      AND db = 'replica'\r\n    GROUP BY time, table_name\r\n),\r\nlag_values AS (\r\n    SELECT time,\r\n           table_name,\r\n           mean_wait_latency,\r\n           LAG(mean_wait_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_wait_latency\r\n    FROM time_buckets\r\n),\r\ntable_latencies AS (\r\n    SELECT table_name,\r\n           SUM(mean_wait_latency - prev_mean_wait_latency) AS total_wait_latency_diff\r\n    FROM lag_values\r\n    WHERE mean_wait_latency - prev_mean_wait_latency IS NOT NULL\r\n    GROUP BY table_name\r\n),\r\ntotal_latency AS (\r\n    SELECT SUM(total_wait_latency_diff) AS overall_total_diff\r\n    FROM table_latencies\r\n),\r\ntable_with_percentage AS (\r\n    SELECT table_name,\r\n           total_wait_latency_diff,\r\n           (total_wait_latency_diff / (SELECT overall_total_diff FROM total_latency)) * 100 AS percentage_of_total\r\n    FROM table_latencies\r\n),\r\ntable_with_cumulative_percentage AS (\r\n    SELECT table_name,\r\n           percentage_of_total,\r\n           SUM(percentage_of_total) OVER (ORDER BY percentage_of_total DESC) AS cumulative_percentage\r\n    FROM table_with_percentage\r\n)\r\nSELECT\r\n    CASE\r\n        WHEN cumulative_percentage - percentage_of_total > 99 THEN 'OTHER'\r\n        ELSE table_name\r\n    END AS table_name,\r\n    SUM(percentage_of_total) AS percentage_of_total\r\nFROM table_with_cumulative_percentage\r\nGROUP BY CASE\r\n            WHEN cumulative_percentage - percentage_of_total > 99 THEN 'OTHER'\r\n            ELSE table_name\r\n         END\r\nORDER BY percentage_of_total DESC;"
    }
   ]
  },
  {
   "title": "Table IO latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (SELECT date_trunc('minute', time) AS time,\r\n                             table_name,\r\n                             AVG(wait_latency)          AS mean_wait_latency\r\n                      FROM table_io\r\n                      WHERE $__timeFilter(time)\r\n                        AND db = 'replica'\r\n                      GROUP BY time, table_name),\r\n     lag_values AS (SELECT time,\r\n                           table_name,\r\n                           mean_wait_latency,\r\n                           LAG(mean_wait_latency)\r\n                           OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_wait_latency\r\n                    FROM time_buckets)\r\nSELECT time,\r\n       table_name,\r\n       mean_wait_latency - prev_mean_wait_latency AS wait_latency_diff\r\nFROM lag_values\r\nWHERE mean_wait_latency - prev_mean_wait_latency IS NOT NULL\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 50 tables by wait latency",
   "type": "table",
   "description": "Top 50 tables by wait latency broken down by operation type",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH time_buckets AS (\r\n    SELECT date_trunc('minute', time) AS time,\r\n           table_name,\r\n           AVG(fetch_latency) AS mean_fetch_latency,\r\n           AVG(insert_latency) AS mean_insert_latency,\r\n           AVG(update_latency) AS mean_update_latency,\r\n           AVG(delete_latency) AS mean_delete_latency,\r\n           AVG(wait_latency) AS mean_wait_latency\r\n    FROM table_io\r\n    WHERE $__timeFilter(time)\r\n      AND db = 'replica'\r\n    GROUP BY time, table_name\r\n),\r\n\r\nlag_values AS (\r\n    SELECT time,\r\n           table_name,\r\n           mean_fetch_latency,\r\n           LAG(mean_fetch_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_fetch_latency,\r\n           mean_insert_latency,\r\n           LAG(mean_insert_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_insert_latency,\r\n           mean_update_latency,\r\n           LAG(mean_update_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_update_latency,\r\n           mean_delete_latency,\r\n           LAG(mean_delete_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_delete_latency,\r\n           mean_wait_latency,\r\n           LAG(mean_wait_latency) OVER (PARTITION BY table_name ORDER BY time) AS prev_mean_wait_latency\r\n    FROM time_buckets\r\n),\r\n\r\nlatency_diffs AS (\r\n    SELECT table_name,\r\n           SUM(mean_fetch_latency - prev_mean_fetch_latency) AS fetch_latency_diff,\r\n           SUM(mean_insert_latency - prev_mean_insert_latency) AS insert_latency_diff,\r\n           SUM(mean_update_latency - prev_mean_update_latency) AS update_latency_diff,\r\n           SUM(mean_delete_latency - prev_mean_delete_latency) AS delete_latency_diff,\r\n           SUM(mean_wait_latency - prev_mean_wait_latency) AS wait_latency_diff\r\n    FROM lag_values\r\n    WHERE mean_wait_latency - prev_mean_wait_latency IS NOT NULL\r\n    GROUP BY table_name\r\n),\r\n\r\noverall_totals AS (\r\n    SELECT SUM(wait_latency_diff) AS overall_wait_diff\r\n    FROM latency_diffs\r\n)\r\n\r\nSELECT table_name,\r\n       ROUND((fetch_latency_diff/NULLIF(wait_latency_diff,0))*100) AS FETCH_LATENCY,\r\n       ROUND((insert_latency_diff/NULLIF(wait_latency_diff,0))*100) AS INSERT_LATENCY,\r\n       ROUND((update_latency_diff/NULLIF(wait_latency_diff,0))*100) AS UPDATE_LATENCY,\r\n       ROUND((delete_latency_diff/NULLIF(wait_latency_diff,0))*100) AS DELETE_LATENCY,\r\n       ROUND((wait_latency_diff/NULLIF(overall_wait_diff,0))*100) AS \"WAIT_LATENCY (percent of total)\"\r\nFROM latency_diffs, overall_totals\r\nWHERE wait_latency_diff >= 0"
    }
   ]
  },
  {
   "title": "Queries by total exec time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_trunc('minute', time) AS time,\r\n    query,\r\n    SUM(exec_time) AS total_execution_time\r\nFROM\r\n    digest_stats\r\nWHERE\r\n    $__timeFilter(time)\r\nAND db = 'replica'\r\nGROUP BY\r\n    time, query\r\nORDER BY\r\n    time;"
    }
   ]
  },
  {
   "title": "Queries by total exec time",
   "type": "table",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n   SUBSTRING(query,1,200) as query, SUM(exec_time)\r\nFROM\r\n    digest_stats\r\nWHERE\r\n    $__timeFilter(time)\r\nAND db = 'replica'\r\ngroup by query\r\norder by 2 desc"
    }
   ]
  }
 ]
}